apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: monitoring
spec:
  version: 8.17.0
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: elasticsearch
  image: registry.local.dev:5001/docker.elastic.co/apm/apm-server:8.17.0
  kibanaRef:
    name: kibana
