apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: elastic-agent
    app.kubernetes.io/version: 8.17.0
  name: elastic-agent
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: elastic-agent
    app.kubernetes.io/version: 8.17.0
  name: elastic-agent
  namespace: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
      - namespaces
      - nodes
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups:
      - extensions
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: elastic-agent
    app.kubernetes.io/version: 8.17.0
  name: elastic-agent
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elastic-agent
subjects:
  - kind: ServiceAccount
    name: elastic-agent
    namespace: monitoring
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: elastic-agent
    app.kubernetes.io/version: 8.17.0
  name: elastic-agent
  namespace: monitoring
spec:
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        serviceAccountName: elastic-agent
  fleetServerRef:
    name: fleet-server
  image: registry.local.dev:5001/docker.elastic.co/beats/elastic-agent:8.17.0
  kibanaRef:
    name: kibana
  mode: fleet
  policyID: eck-agent
  version: 8.17.0
