apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/version: 8.17.0
  name: fleet-server
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/version: 8.17.0
  name: fleet-server
  namespace: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/version: 8.17.0
  name: fleet-server
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fleet-server
subjects:
  - kind: ServiceAccount
    name: fleet-server
    namespace: monitoring
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/version: 8.17.0
  name: fleet-server
  namespace: monitoring
spec:
  deployment:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        serviceAccountName: fleet-server
    replicas: 1
  elasticsearchRefs:
    - name: elasticsearch
  fleetServerEnabled: true
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  image: registry.local.dev:5001/docker.elastic.co/beats/elastic-agent:8.17.0
  kibanaRef:
    name: kibana
  mode: fleet
  policyID: eck-fleet-server
  version: 8.17.0
