apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: elastic-agent
    app.kubernetes.io/version: {{ .Values.imageTag }}
  name: elastic-agent
