image:
  crdRepository: registry.local.dev:5001/openpolicyagent/gatekeeper-crds
  repository: registry.local.dev:5001/openpolicyagent/gatekeeper
  release: v3.18.2
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "8888"
postInstall:
  labelNamespace:
    image:
      repository: registry.local.dev:5001/openpolicyagent/gatekeeper-crds
      tag: v3.18.2
  probeWebhook:
    image:
      repository: registry.local.dev:5001/curlimages/curl
      tag: 8.12.1
postUpgrade:
  labelNamespace:
    image:
      repository: registry.local.dev:5001/openpolicyagent/gatekeeper-crds
      tag: v3.18.2
preInstall:
  crdRepository:
    image:
      repository: registry.local.dev:5001/openpolicyagent/gatekeeper-crds
      tag: v3.18.2
preUninstall:
  deleteWebhookConfigurations:
    image:
      repository: registry.local.dev:5001/openpolicyagent/gatekeeper-crds
      tag: v3.18.2
replicas: 1
