args:
  - --kubelet-insecure-tls

commonLabels:
  app.kubernetes.io/name: metrics-server

metrics:
  enabled: true

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus

nodeSelector:
  kubernetes.io/os: linux
