args:
  - --kubelet-insecure-tls
commonLabels:
  app.kubernetes.io/name: metrics-server
image:
  repository: registry.local.dev:5001/registry.k8s.io/metrics-server/metrics-server
  tag: v0.7.2
metrics:
  enabled: true
serviceMonitor:
  additionalLabels:
    release: kube-prometheus
  enabled: true
nodeSelector:
  kubernetes.io/os: linux
