replicaCount: 1
ingress:
  annotations:
    external-dns.alpha.kubernetes.io/target: local.dev
  enabled: true
  className: traefik
  hosts:
    - host: podinfo.local.dev
      paths:
        - path: /
          pathType: Prefix
