image:
  repository: registry.local.dev:5001/ghcr.io/stefanprodan/podinfo
  tag: 6.7.1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    external-dns.alpha.kubernetes.io/target: local.dev
  className: traefik
  enabled: true
  hosts:
    - host: podinfo.local.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - podinfo.local.dev
      secretName: podinfo-tls
nodeSelector:
  kubernetes.io/os: linux
replicaCount: 1
serviceAccount:
  create: true
