replicaCount: 1
ingress:
  annotations:
    external-dns.alpha.kubernetes.io/target: local.dev
    cert-manager.io/cluster-issuer: ca-issuer
  enabled: true
  className: traefik
  hosts:
    - host: podinfo.local.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - podinfo.local.dev
      secretName: podinfo-cert
