grafana:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      external-dns.alpha.kubernetes.io/target: local.dev
    enabled: true
    hosts:
      - grafana.local.dev
    ingressClassName: traefik
    tls:
      - hosts:
          - grafana.local.dev
        secretName: grafana-tls

prometheus:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      external-dns.alpha.kubernetes.io/target: local.dev
    enabled: true
    hosts:
      - prometheus.local.dev
    ingressClassName: traefik
    tls:
      - hosts:
          - prometheus.local.dev
        secretName: prometheus-tls
