grafana:
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: local.dev
      cert-manager.io/cluster-issuer: ca-issuer
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.local.dev
    path: /
    tls:
      - hosts:
          - grafana.local.dev
        secretName: grafana-cert

prometheus:
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: local.dev
      cert-manager.io/cluster-issuer: ca-issuer
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.local.dev
    paths:
      - /
    tls:
      - hosts:
          - prometheus.local.dev
        secretName: prometheus-cert
