alertmanager:
  annotations: {}
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      external-dns.alpha.kubernetes.io/target: local.dev
      friendly-name: Alert Manager
    enabled: true
    hosts:
      - alertmanager.local.dev
    ingressClassName: traefik
    paths:
      - /
    tls:
      - hosts:
          - alertmanager.local.dev
        secretName: alertmanager-tls
  alertmanagerSpec:
    image:
      registry: registry.local.dev:5001
      repository: quay.io/prometheus/alertmanager
      tag: v0.28.0
    nodeSelector:
      kubernetes.io/os: linux
crds:
  upgradeJob:
    image:
      busybox:
        registry: registry.local.dev:5001
        repository: docker.io/busybox
        tag: 1.37.0
grafana:
  adminUser: grafana
  grafana.ini:
    analytics:
      check_for_updates: false
  image:
    registry: registry.local.dev:5001
    repository: docker.io/grafana/grafana
    tag: 11.4.0
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      credentials-password-jsonpath: "{.data.admin-password}"
      credentials-password-secret: kube-prometheus-grafana
      credentials-username: grafana
      external-dns.alpha.kubernetes.io/target: local.dev
      friendly-name: Grafana
    enabled: true
    hosts:
      - grafana.local.dev
    ingressClassName: traefik
    tls:
      - hosts:
          - grafana.local.dev
        secretName: grafana-tls
  initChownData:
    image:
      registry: registry.local.dev:5001
      repository: docker.io/library/busybox
      tag: 1.31.1
  nodeSelector:
    kubernetes.io/os: linux
  persistence:
    enabled: true
    size: 5Gi
  sidecar:
    alertmanager:
      enabled: false
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      provider:
        allowUiUpdates: true
        foldersFromFilesStructure: true
      searchNamespace: ALL
    image:
      registry: registry.local.dev:5001
      repository: quay.io/kiwigrid/k8s-sidecar
      tag: 1.28.0
  testFramework:
    enabled: false
kube-state-metrics:
  nodeSelector:
    kubernetes.io/os: linux
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
nodeExporter:
  operatingSystems:
    aix:
      enabled: false
    darwin:
      enabled: false
prometheus:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      external-dns.alpha.kubernetes.io/target: local.dev
      friendly-name: Prometheus
    enabled: true
    hosts:
      - prometheus.local.dev
    ingressClassName: traefik
    tls:
      - hosts:
          - prometheus.local.dev
        secretName: prometheus-tls
  nodeSelector:
    kubernetes.io/os: linux
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            action: keep
            regex: true
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels:
              - __meta_kubernetes_namespace
            action: replace
            target_label: kubernetes_namespace
          - source_labels:
              - __meta_kubernetes_pod_name
            action: replace
            target_label: kubernetes_pod_name
    image:
      registry: registry.local.dev:5001
      repository: quay.io/prometheus/prometheus
      tag: v3.1.0
  storageSpec:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
prometheus-node-exporter:
  image:
    registry: registry.local.dev:5001
    repository: quay.io/prometheus/node-exporter
    tag: v1.8.2
  nodeSelector:
    kubernetes.io/os: linux
prometheusOperator:
  admissionWebhooks:
    deployment:
      image:
        registry: registry.local.dev:5001
        repository: quay.io/prometheus-operator/admission-webhook
        tag: v0.79.2
    patch:
      image:
        registry: registry.local.dev:5001
        repository: registry.k8s.io/ingress-nginx/kube-webhook-certgen
        tag: v1.5.1
  image:
    registry: registry.local.dev:5001
    repository: quay.io/prometheus-operator/prometheus-operator
    tag: v0.79.2
  nodeSelector:
    kubernetes.io/os: linux
  prometheusConfigReloader:
    image:
      registry: registry.local.dev:5001
      repository: quay.io/prometheus-operator/prometheus-config-reloader
      tag: v0.79.2
