grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.local.dev
    path: /

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.local.dev
    paths:
      - /
