ui:
  dockerRegistryUrl: "https://registry.local.dev:5001"

  deleteImages: true

  ingress:
    enabled: true
    host: registry.local.dev
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      external-dns.alpha.kubernetes.io/target: local.dev
    tls:
      - secretName: registry-ui-tls
        hosts:
          - registry.local.dev

  title: "Local Dev Registry"
