ui:
  title: "Local Development Registry"
  dockerRegistryUrl: "https://registry.local.dev:5001"
  deleteImages: true

  ingress:
    enabled: true
    ingressClassName: traefik
    host: registry.local.dev
    path: /
    pathType: Prefix
    annotations:
      external-dns.alpha.kubernetes.io/target: local.dev
      cert-manager.io/cluster-issuer: ca-issuer
    tls:
      - secretName: registry-tls
        hosts:
          - registry.local.dev
