ui:
  catalogDefaultExpanded: true

  dockerRegistryUrl: "https://registry.local.dev:5001"

  deleteImages: true

  image: registry.local.dev:5001/joxit/docker-registry-ui:2.5.2

  ingress:
    enabled: true
    host: registry.local.dev
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      external-dns.alpha.kubernetes.io/target: local.dev
    tls:
      - secretName: registry-ui-tls
        hosts:
          - registry.local.dev

  nodeSelector:
    kubernetes.io/os: linux

  title: "Local Dev Registry"
