ui:
  catalogDefaultExpanded: true
  dockerRegistryUrl: https://registry.local.dev:5001
  deleteImages: true
  image: registry.local.dev:5001/joxit/docker-registry-ui:2.5.2
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      external-dns.alpha.kubernetes.io/target: local.dev
      friendly-name: Container Registry
    enabled: true
    host: registry.local.dev
    ingressClassName: traefik
    tls:
      - hosts:
          - registry.local.dev
        secretName: registry-ui-tls
  nodeSelector:
    kubernetes.io/os: linux
  title: "registry.local.dev:5001"
