persistence:
  enabled: true
  size: 10Gi
service:
  type: ClusterIP
ingress:
  annotations:
    external-dns.alpha.kubernetes.io/target: local.dev
    cert-manager.io/cluster-issuer: ca-issuer
  enabled: true
  className: traefik
  hosts:
    - registry.local.dev
  tls:
    - secretName: registry-tls
      hosts:
        - registry.local.dev
