ingressRoute:
  dashboard:
    annotations:
      external-dns.alpha.kubernetes.io/target: local.dev
      cert-manager.io/cluster-issuer: ca-issuer
    enabled: true
    entryPoints:
      - web
      - websecure
    matchRule: Host(`traefik.local.dev`)
    tls:
      secretName: traefik-cert
      domains:
        - main: traefik.local.dev

ports:
  web:
    nodePort: 30080
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    nodePort: 30443
    tls:
      enabled: true

service:
  type: NodePort
