additionalArguments:
  - --entrypoints.web.http.encodequerysemicolons=true
  - --entrypoints.websecure.http.encodequerysemicolons=true

globalArguments:

ingressRoute:
  dashboard:
    annotations:
      external-dns.alpha.kubernetes.io/target: local.dev
    enabled: true
    entryPoints:
      - web
      - websecure
    matchRule: Host(`traefik.local.dev`)
    tls:
      secretName: traefik-tls
      domains:
        - main: traefik.local.dev

nodeSelector:
  kubernetes.io/os: linux

ports:
  web:
    forwardedHeaders:
      insecure: true
    nodePort: 30080
    redirections:
      entryPoint:
        permanent: true
        scheme: https
        to: websecure
  websecure:
    nodePort: 30443
    tls:
      enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowEmptyServices: true
    allowExternalNameServices: true
  kubernetesIngress:
    allowEmptyServices: true
    allowExternalNameServices: true

service:
  type: NodePort
