additionalArguments:
  - --entrypoints.web.http.encodequerysemicolons=true
  - --entrypoints.websecure.http.encodequerysemicolons=true
commonLabels:
  app.kubernetes.io/version: 34.1.0
globalArguments:
image:
  registry: registry.local.dev:5001
  repository: docker.io/traefik
  tag: v3.3.2
ingressRoute:
  dashboard:
    annotations:
      external-dns.alpha.kubernetes.io/target: local.dev
    enabled: true
    entryPoints:
      - web
      - websecure
    matchRule: Host(`traefik.local.dev`)
    tls:
      secretName: traefik-tls
      domains:
        - main: traefik.local.dev
metrics:
  addInternals: true
  prometheus:
    serviceMonitor:
      additionalLabels:
        release: kube-prometheus
      enabled: true
  otlp:
    enabled: true
    http:
      enabled: true
      endpoint: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/metrics
nodeSelector:
  kubernetes.io/os: linux
ports:
  web:
    forwardedHeaders:
      insecure: true
    nodePort: 30080
    redirections:
      entryPoint:
        permanent: true
        scheme: https
        to: websecure
  websecure:
    nodePort: 30443
    tls:
      enabled: true
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowEmptyServices: true
    allowExternalNameServices: true
  kubernetesIngress:
    allowEmptyServices: true
    allowExternalNameServices: true
service:
  type: NodePort
tracing:
  addInternals: true
  otlp:
    enabled: true
    http:
      enabled: true
      endpoint: http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/traces
