ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web
      - websecure
    matchRule: Host(`traefik.local.dev`)

ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443

service:
  type: NodePort
