ingressRoute:
  dashboard:
    annotations:
      external-dns.alpha.kubernetes.io/target: local.dev
    enabled: true
    entryPoints:
      - web
      - websecure
    matchRule: Host(`traefik.local.dev`)
    tls:
      secretName: traefik-tls
      domains:
        - main: traefik.local.dev

ports:
  web:
    nodePort: 30080
    redirections:
      entryPoint:
        permanent: true
        scheme: https
        to: websecure
  websecure:
    nodePort: 30443
    tls:
      enabled: true

service:
  type: NodePort
