ingressRoute:
  dashboard:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: traefik.local.dev
    enabled: true
    entryPoints:
      - web
      - websecure
    matchRule: Host(`traefik.local.dev`)

ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443

service:
  type: NodePort
