apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry
  namespace: registry
spec:
  commonName: registry.local.dev
  secretName: registry
  dnsNames:
    - registry.local.dev
    - registry
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
