apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: apm-server
    app.kubernetes.io/version: {{ .Values.imageTag }}
  name: apm-server
spec:
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  image: registry.local.dev:5001/docker.elastic.co/apm/apm-server:{{ .Values.imageTag }}
  kibanaRef:
    name: kibana
  version: {{ .Values.imageTag }}
