repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: strimzi
    url: https://strimzi.io/charts/

helmDefaults:
  atomic: true
  cleanupOnFail: true
  timeout: 600
  wait: true

releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 41.0.2
    labels:
      profile: core
    values:
      - values/traefik.yaml

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.21.0
    labels:
      profile: core
    values:
      - values/cert-manager.yaml

  - name: alloy
    namespace: observability
    createNamespace: true
    chart: grafana/alloy
    version: 1.10.1
    labels:
      profile: core
    values:
      - values/alloy.yaml

  - name: cloudnative-pg
    namespace: cnpg-system
    createNamespace: true
    chart: cnpg/cloudnative-pg
    version: 0.29.0
    labels:
      profile: core
    values:
      - values/cloudnative-pg.yaml

  - name: strimzi
    namespace: kafka-system
    createNamespace: true
    chart: strimzi/strimzi-kafka-operator
    version: 1.1.0
    labels:
      profile: full
    values:
      - values/strimzi.yaml
