repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: jetstack
    url: https://charts.jetstack.io

helmDefaults:
  atomic: true
  cleanupOnFail: true
  timeout: 600
  wait: true

releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 41.0.2
    labels:
      profile: core
    values:
      - values/traefik.yaml

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.21.0
    labels:
      profile: core
    values:
      - values/cert-manager.yaml
