apiVersion: v1
kind: Namespace
metadata:
  name: bind9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
  namespace: bind9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
      - name: bind9
        image: localhost:5000/bind9:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: bind9
  namespace: bind9
spec:
  type: ClusterIP
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
    app: bind9
---
apiVersion: v1
kind: Service
metadata:
  name: bind9-public
  namespace: bind9
spec:
  type: NodePort
  ports:
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
    nodePort: 30053
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
    nodePort: 30053
  selector:
    app: bind9
