apiVersion: v1
kind: Namespace
metadata:
  name: dns
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: bind9
    app.kubernetes.io/name: bind9
    app.kubernetes.io/version: 9.18-22.04_beta
  name: bind9
  namespace: dns
data:
  named.conf.options: |
    acl internal {
      10.0.0.0/8;
      172.16.0.0/12;
      192.168.0.0/16;
      localhost;
      localnets;
    };

    options {
      directory "/var/cache/bind";

      # Forwarders configuration
      forwarders {
        8.8.8.8;
        8.8.4.4;
      };
      forward only;

      # Network configuration
      listen-on port 53 { any; };
      listen-on-v6 { none; };
      allow-query { internal; };
      allow-recursion { internal; };
      allow-query-cache { internal; };

      # Performance tuning
      max-cache-size 256m;
      max-cache-ttl 86400;
      max-ncache-ttl 3600;
      recursive-clients 3000;
      tcp-clients 2000;

      # Security settings
      version "not disclosed";
      dnssec-validation auto;
      auth-nxdomain no;
      empty-zones-enable yes;

      # Rate limiting to prevent DNS amplification attacks
      rate-limit {
        responses-per-second 20;
        window 5;
      };

      # Memory and transfer tuning
      transfer-format many-answers;
      transfers-in 10;
      transfers-out 10;
      transfers-per-ns 2;
    };

    # Statistics configuration
    statistics-channels {
      inet 127.0.0.1 port 8053 allow { 127.0.0.1; };
    };

    # Logging configuration
    logging {
      channel default_log {
        file "/var/log/named/default.log" versions 3 size 20m;
        severity info;
        print-time yes;
        print-severity yes;
        print-category yes;
      };

      channel query_log {
        file "/var/log/named/query.log" versions 3 size 20m;
        severity info;
        print-time yes;
      };

      category default { default_log; };
      category queries { query_log; };
    };

  named.conf.local: |
    key "externaldns-key" {
        algorithm hmac-sha256;
        secret "0Z/s3fhefz8Kq3xHNOYaiEvBHsdxEsRMyEx29b5SBLY=";
    };

    zone "local.dev" {
        type master;
        file "/var/cache/bind/local.dev.zone";
        allow-transfer { key externaldns-key; };
        update-policy {
            grant externaldns-key zonesub ANY;
        };
    };


  local.dev.zone: |
    $TTL    86400
    @       IN      SOA     local.dev. root.local.dev. (
                            2023111001      ; Serial
                            3600            ; Refresh
                            1800            ; Retry
                            604800          ; Expire
                            86400           ; Minimum TTL
    )
    @       IN      NS      ns.local.dev.
    @       IN      A       127.0.0.1
    ns      IN      A       127.0.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: bind9
    app.kubernetes.io/name: bind9
    app.kubernetes.io/version: 9.18-22.04_beta
  name: bind9
  namespace: dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bind9
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bind9
        app.kubernetes.io/name: bind9
        app.kubernetes.io/version: 9.18-22.04_beta
    spec:
      containers:
        - command:
            - /usr/sbin/named
          args:
            - -g
            - -c
            - /etc/bind/named.conf
          image: registry.local.dev:5001/ubuntu/bind9:9.18-22.04_beta
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 53
          name: bind9
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 8053
              name: stats
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 53
          volumeMounts:
            - mountPath: /etc/bind/named.conf.options
              name: config
              subPath: named.conf.options
            - mountPath: /etc/bind/named.conf.local
              name: config
              subPath: named.conf.local
            - mountPath: /var/cache/bind/local.dev.zone
              name: config
              subPath: local.dev.zone
            - mountPath: /var/log/named
              name: bind-logs
        - args:
            - --bind.stats-groups=server,view
            - --bind.stats-url=http://localhost:8053/
            - --bind.timeout=20s
            - --web.listen-address=:9119
          image: registry.local.dev:5001/prometheuscommunity/bind-exporter:v0.6.0
          name: bind-exporter
          ports:
            - containerPort: 9119
              name: metrics
      volumes:
        - configMap:
            name: bind9
          name: config
        - emptyDir: {}
          name: bind-logs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bind9
    app.kubernetes.io/name: bind9
    app.kubernetes.io/version: 9.18-22.04_beta
  name: bind9
  namespace: dns
spec:
  ports:
    - name: dns-udp
      nodePort: 30053
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      nodePort: 30053
      port: 53
      protocol: TCP
      targetPort: 53
    - name: stats
      targetPort: 8053
      port: 8053
      protocol: TCP
    - name: metrics
      port: 9119
      protocol: TCP
      targetPort: 9119
  selector:
    app.kubernetes.io/name: bind9
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: bind9
    app.kubernetes.io/name: bind9
    app.kubernetes.io/version: 9.18-22.04_beta
    release: kube-prometheus
  name: bind9
  namespace: dns
spec:
  endpoints:
    - port: metrics
  jobLabel: bind9
  selector:
    matchLabels:
      app.kubernetes.io/name: bind9
