apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: v0.15.1
  name: external-dns
  namespace: dns
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: v0.15.1
  name: external-dns
  namespace: dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: v0.15.1
  name: external-dns-viewer
  namespace: dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: v0.15.1
  name: external-dns
  namespace: dns
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: external-dns
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/version: v0.15.1
    spec:
      containers:
        - args:
            - --registry=txt
            - --txt-prefix=external-dns-
            - --txt-owner-id=k8s
            - --provider=rfc2136
            - --rfc2136-host=bind9
            - --rfc2136-port=53
            - --rfc2136-zone=local.dev
            - --rfc2136-tsig-secret=0Z/s3fhefz8Kq3xHNOYaiEvBHsdxEsRMyEx29b5SBLY=
            - --rfc2136-tsig-secret-alg=hmac-sha256
            - --rfc2136-tsig-keyname=externaldns-key
            - --rfc2136-tsig-axfr
            - --source=service
            - --source=ingress
            - --source=traefik-proxy
            - --domain-filter=local.dev
            - --traefik-disable-legacy
            - --interval=15s
            - --metrics-address=:7979
            - --log-level=info
            - --policy=sync
          image: registry.local.dev:5001/registry.k8s.io/external-dns/external-dns:v0.15.1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7979
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: external-dns
          ports:
            - containerPort: 7979
              name: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: 7979
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: external-dns
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: v0.15.1
    release: kube-prometheus
  name: external-dns
  namespace: dns
spec:
  endpoints:
    - port: metrics
  jobLabel: external-dns
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: v0.15.1
  name: external-dns
  namespace: dns
spec:
  ports:
  - name: metrics
    port: 7979
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: external-dns
  type: ClusterIP
