replicaCount: 1

image:
  repository: registry.local.dev:5001/weather-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  annotations:
    external-dns.alpha.kubernetes.io/target: local.dev
    cert-manager.io/cluster-issuer: ca-issuer
  hosts:
    - host: weather.local.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: weather-tls
      hosts:
        - weather.local.dev

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
