apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    credentials-password-jsonpath: "{.data.elastic}"
    credentials-password-secret: elasticsearch-es-elastic-user
    credentials-username: elastic
    external-dns.alpha.kubernetes.io/target: local.dev
    friendly-name: Kibana
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: kibana
    app.kubernetes.io/version: {{ .Values.imageTag }}
  name: kibana
spec:
  rules:
    - host: kibana.local.dev
      http:
        paths:
          - backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - kibana.local.dev
      secretName: kibana-tls
