apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: kibana
    app.kubernetes.io/version: 8.17.0
  name: kibana
spec:
  config:
    server.publicBaseUrl: https://kibana.local.dev
    xpack.fleet.agents.elasticsearch.hosts:
      - http://elasticsearch-es-http.monitoring.svc.cluster.local:9200
    xpack.fleet.agents.fleet_server.hosts:
      - http://fleet-server-agent-http.monitoring.svc.cluster.local:8220
    xpack.fleet.packages:
      - name: apm
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: kubernetes
        version: latest
      - name: system
        version: latest
    xpack.fleet.agentPolicies:
      - id: eck-fleet-server
        is_managed: true
        monitoring_enabled:
          - logs
          - metrics
        name: Fleet Server on ECK policy
        namespace: {{ .Release.Namespace}}
        package_policies:
          - id: fleet_server-1
            name: fleet_server-1
            package:
              name: fleet_server
        unenroll_timeout: 900
      - id: eck-agent
        is_managed: true
        monitoring_enabled:
          - logs
          - metrics
        name: Elastic Agent on ECK policy
        namespace: {{ .Release.Namespace}}
        package_policies:
          - name: system-1
            package:
              name: system
          - name: kubernetes-1
            package:
              name: kubernetes
        unenroll_timeout: 900
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  image: registry.local.dev:5001/docker.elastic.co/kibana/kibana:8.17.0
  version: 8.17.0
