apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: bind9
    app.kubernetes.io/name: bind9
    app.kubernetes.io/version: 9.18-22.04_beta
  name: bind9
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bind9
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bind9
        app.kubernetes.io/name: bind9
        app.kubernetes.io/version: 9.18-22.04_beta
    spec:
      containers:
        - args:
            - -g
            - -c
            - /etc/bind/named.conf
          command:
            - /usr/sbin/named
          image: registry.local.dev:5001/ubuntu/bind9:9.18-22.04_beta
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 53
          name: bind9
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 8053
              name: stats
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 53
          volumeMounts:
            - mountPath: /etc/bind/named.conf.options
              name: config
              subPath: named.conf.options
            - mountPath: /etc/bind/named.conf.local
              name: config
              subPath: named.conf.local
            - mountPath: /var/cache/bind/local.dev.zone
              name: config
              subPath: local.dev.zone
            - mountPath: /var/log/named
              name: bind-logs
        - args:
            - --bind.stats-groups=server,view
            - --bind.stats-url=http://localhost:8053/
            - --bind.timeout=20s
            - --web.listen-address=:9119
          image: registry.local.dev:5001/prometheuscommunity/bind-exporter:v0.6.0
          name: bind-exporter
          ports:
            - containerPort: 9119
              name: metrics
      volumes:
        - configMap:
            name: bind9
          name: config
        - emptyDir: {}
          name: bind-logs
