apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bind9
    app.kubernetes.io/name: bind9
    app.kubernetes.io/version: 9.18-22.04_beta
  name: bind9
spec:
  ports:
    - name: dns-udp
      nodePort: 30053
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      nodePort: 30053
      port: 53
      protocol: TCP
      targetPort: 53
    - name: stats
      targetPort: 8053
      port: 8053
      protocol: TCP
    - name: metrics
      port: 9119
      protocol: TCP
      targetPort: 9119
  selector:
    app.kubernetes.io/name: bind9
  type: NodePort
