apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: latest
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    external-dns.alpha.kubernetes.io/target: local.dev
spec:
  ingressClassName: traefik
  rules:
    - host: weather.local.dev
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - weather.local.dev
      secretName: weather-tls

