apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik
  namespace: traefik
spec:
  commonName: traefik.local.dev
  dnsNames:
    - traefik.local.dev
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: traefik-tls
