apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.16.3
  name: ca-key-pair
data:
  tls.crt: {{ .Values.ca.crt }}
  tls.key: {{ .Values.ca.key }}
