apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: v0.15.1
  name: external-dns
spec:
  ports:
  - name: metrics
    port: 7979
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: external-dns
  type: ClusterIP
