apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.local.dev:5001"]
      endpoint = ["https://registry:443"]
nodes:
  - role: control-plane
    extraMounts:
      - containerPath: /usr/local/share/ca-certificates/ca.crt
        hostPath: $PWD/temp/secrets/ca.crt
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
      - containerPort: 30443
        hostPort: 443
      - containerPort: 30053
        hostPort: 53
        protocol: UDP
      - containerPort: 30053
        hostPort: 53
        protocol: TCP
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
  - role: worker
    extraMounts:
      - containerPath: /usr/local/share/ca-certificates/ca.crt
        hostPath: $PWD/temp/secrets/ca.crt
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
  - role: worker
    extraMounts:
      - containerPath: /usr/local/share/ca-certificates/ca.crt
        hostPath: $PWD/temp/secrets/ca.crt
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
  - role: worker
    extraMounts:
      - containerPath: /usr/local/share/ca-certificates/ca.crt
        hostPath: $PWD/temp/secrets/ca.crt
    image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
