apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/version: {{ .Values.imageTag }}
  name: fleet-server
spec:
  deployment:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        serviceAccountName: fleet-server
    replicas: 1
  elasticsearchRefs:
    - name: elasticsearch
  fleetServerEnabled: true
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  image: registry.local.dev:5001/docker.elastic.co/beats/elastic-agent:{{ .Values.imageTag }}
  kibanaRef:
    name: kibana
  mode: fleet
  policyID: eck-fleet-server
  version: {{ .Values.imageTag }}
