apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/version: {{ .Values.imageTag }}
  name: fleet-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fleet-server
subjects:
  - kind: ServiceAccount
    name: fleet-server
    namespace: {{ .Release.Namespace}}
