apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: eck-stack
    app.kubernetes.io/name: fleet-server
    app.kubernetes.io/version: {{ .Values.imageTag }}
  name: fleet-server
